Fiat-Shamir zk Protocol
WeBankBlockchain/SmartDev-Contract pull request #12
Opened 2021-06-15 05:34 UTC by bo-hub

First pull request of Fiat-Shamir zk Protocol

2021-06-17 08:31 UTC, dalaocu requested changes

2021-06-17 08:31 UTC, dalaocu commented on contracts/privacy_computation/Fiat-Shamir-ZK/FiatShamir.sol
> +contract FiatShamirZK {
文件名需要和合约名称保持一致。

2021-06-17 08:31 UTC, dalaocu commented on contracts/privacy_computation/Fiat-Shamir-ZK/README.md
> +## 使用
使用步骤建议细化补充下。

2021-06-18 02:54 UTC, bo-hub commented
修改合约名与使用步骤

2021-06-19 13:21 UTC, dalaocu approved these changes

2021-06-19 13:21 UTC, merged