Task52,54单车代码注释和bug修复
WeBankBlockchain/SmartDev-Contract pull request #143
Opened 2023-08-17 03:56 UTC by tttwei

2023-10-16 07:11 UTC, tttwei commented
首先在构造方法这里，原本是没有用UserStorage的地址构造的，导致获取到的UserStorage对象没有值，这里把UserStorage的合约地址值作为构造条件添加上去了，另外我在加分减分这里还做了一些优化比如防止溢出什么的，还有原代码有些明显的错误比如userstorage中的48和56行，在这里的判断比较也不应该这样比，而应该用老分数个新分数比较，而不应该把新分数和加减多少分做比较。这里应该是想这样，用老分数和新分数比，而原来的代码忽略了这样的问题，选择错了对象。

2023-10-16 07:13 UTC, tttwei commented
所以在新提交的代码中我优化了相关的代码，即使超出范围也可以自动处理，而不是用require报错代替

2023-10-16 07:32 UTC, tttwei commented
userstorage的注册user方法中（37行位置）也没有对user的status进行修改，我添加上了

2023-10-16 07:55 UTC, tttwei commented
sharedbike的94行fix单车方法中修改了错误的状态，应该把单车状态修改为可以使用

2023-10-25 08:03 UTC, dalaocu requested changes

2023-10-25 08:03 UTC, dalaocu commented on contracts/business_template/shared_bike/UserStorage.sol
> +        //添加if判断，防止溢出
这里之前的代码已经做了防止溢出的检查了

2023-10-25 08:03 UTC, dalaocu commented on contracts/business_template/shared_bike/SharedBike.sol
> +        Bike storage bike = _bikes[bikeId];
这里没看到对bike的后续处理

2023-10-25 08:18 UTC, tttwei commented on contracts/business_template/shared_bike/UserStorage.sol
> +        //添加if判断，防止溢出
做了但判断的对象错了，这里应该是要对比新值和旧值，看代码56行，减分数方法，如果一共10分，我调用方法扣1分，newPoint将会是9分，当执行到require(newPoint < credits, "overflow");时，credits=1，newPoint=9,9<1为false,这里就会报错，按理说10分，扣1分，能扣吧，而在这种情况将会报错

2023-10-25 10:13 UTC, dalaocu approved these changes

2023-10-25 10:13 UTC, merged