Task51 & Task52 给MultiSignDemo.sol、MultiSign、Licences.sol合约添加代码注释
WeBankBlockchain/SmartDev-Contract pull request #159
Opened 2023-09-14 04:13 UTC by Mr-Ghost552

作者：罗嘉城
学校：深圳信息职业技术学院

2023-09-15 08:40 UTC, dalaocu requested changes

2023-09-15 08:40 UTC, dalaocu commented on contracts/common_tools/MultiSign/MultiSign.sol
> +对交易进行签名，当达到最小签名要求时，交易将被标记为已完成。这是一个常用的多签名合约模式，用于确保多个授权者的参与。注意，这
这段注释换行了。。。
另外，这段注释建议挪到最上面

2023-09-15 08:40 UTC, dalaocu commented on contracts/common_tools/MultiSign/MultiSignDemo.sol
> +与交易相关的信息，并在签名过程完成时跟踪回调次数。合约构造函数初始化了所有者的地址，并从父合约设置了必要的参数。覆盖的 signFinishedCallBack 函数在交易
同上

2023-09-16 09:55 UTC, Mr-Ghost552 commented on contracts/common_tools/MultiSign/MultiSignDemo.sol
> +与交易相关的信息，并在签名过程完成时跟踪回调次数。合约构造函数初始化了所有者的地址，并从父合约设置了必要的参数。覆盖的 signFinishedCallBack 函数在交易
已修改

2023-09-18 03:00 UTC, dalaocu requested changes

2023-09-18 03:00 UTC, dalaocu commented on contracts/common_tools/MultiSign/MultiSignDemo.sol
>  // SPDX-License-Identifier: UNLICENSED
同上

2023-09-18 06:37 UTC, Mr-Ghost552 commented on contracts/common_tools/MultiSign/MultiSignDemo.sol
>  // SPDX-License-Identifier: UNLICENSED
已修改

2023-09-21 03:58 UTC, dalaocu approved these changes

2023-09-21 03:58 UTC, merged