add a Character.sol
WeBankBlockchain/SmartDev-Contract pull request #16
Opened 2021-06-16 14:27 UTC by Blockchain-Key

该合约写了一个库合约Role，包含增删改查介绍，基于合约Character实现库合约Role相关方法

2021-06-17 03:35 UTC, dalaocu commented
可否添加下文档？

2021-06-18 07:54 UTC, dalaocu requested changes

2021-06-18 07:54 UTC, dalaocu commented on contracts/Role_operation/Character.sol
> +
可否补充下文档？谢谢。

2021-06-19 07:25 UTC, Blockchain-Key commented on contracts/Role_operation/Character.sol
> +
okok，昨天比较忙，今明两天补充下文档

2021-06-21 02:30 UTC, dalaocu approved these changes

2021-06-21 02:31 UTC, merged